version: '3'
services:
  # Web Service Tanımı
  webapp:
    build: ./webapp
    ports:
      - "1010:8080"
    depends_on:
      - db
    volumes:
      - ./webapp:/app
      - node_modules:/app/node_modules
    networks:
      - app-networks

  # Database Tanımı
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-networks

# Network Tanımı
networks:
  app-networks:

# Volume Tanımı
volumes:
  node_modules:
  dbdata:
